#! /bin/sh
docker run --ipc host -p 8888:80 -v /mnt/log:/var/log tuonglan/simple-server:$(cat VERSION) /usr/local/bin/python /opt/lando/simple-server/server-daemon.py --update_nginx --port_range 8000:8010
